# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_dense_dist <- function(dist_type, XIX, xmat, YIX, ymat, pairwise = FALSE, self = FALSE) {
    .Call('_simdist_C_dense_dist', PACKAGE = 'simdist', dist_type, XIX, xmat, YIX, ymat, pairwise, self)
}

C_dense_range_dist <- function(dist_type, xrange, XV, yrange, YV, self = FALSE) {
    .Call('_simdist_C_dense_range_dist', PACKAGE = 'simdist', dist_type, xrange, XV, yrange, YV, self)
}

C_sparse_dist <- function(dist_type, XIX, XP, XV, YIX, YP, YV, out_rows, out_cols, pairwise = FALSE, self = FALSE, xreorder = 0L, yreorder = 0L) {
    .Call('_simdist_C_sparse_dist', PACKAGE = 'simdist', dist_type, XIX, XP, XV, YIX, YP, YV, out_rows, out_cols, pairwise, self, xreorder, yreorder)
}

C_triplet_dist <- function(dist_type, xpri, xsec, xval, ypri, ysec, yval, out_rows, out_cols, pairwise = FALSE, self = FALSE, xreorder = 0L, yreorder = 0L) {
    .Call('_simdist_C_triplet_dist', PACKAGE = 'simdist', dist_type, xpri, xsec, xval, ypri, ysec, yval, out_rows, out_cols, pairwise, self, xreorder, yreorder)
}

C_sparse_aggr_dist <- function(aggr_type, dist_type, vecs, XIX, XP, XV, YIX, YP, YV, out_rows, out_cols, pairwise = FALSE, self = FALSE, precompute = TRUE) {
    .Call('_simdist_C_sparse_aggr_dist', PACKAGE = 'simdist', aggr_type, dist_type, vecs, XIX, XP, XV, YIX, YP, YV, out_rows, out_cols, pairwise, self, precompute)
}

C_triplet_aggr_dist <- function(aggr_type, dist_type, vecs, xpri, xsec, xval, ypri, ysec, yval, out_rows, out_cols, pairwise = FALSE, self = FALSE, precompute = TRUE) {
    .Call('_simdist_C_triplet_aggr_dist', PACKAGE = 'simdist', aggr_type, dist_type, vecs, xpri, xsec, xval, ypri, ysec, yval, out_rows, out_cols, pairwise, self, precompute)
}

